/**
 * Build script for CEE Mock Portal (all-in-one deployment).
 * Reads Code.gs and index.html, base64-encodes the HTML, and writes cee_mock_all_in_one.gs.
 */

const fs = require('fs');
const path = require('path');

const CODE_GS_PATH = path.join(__dirname, '..', 'Code.gs');
const INDEX_HTML_PATH = path.join(__dirname, '..', 'index.html');
const OUTPUT_PATH = path.join(__dirname, '..', 'cee_mock_all_in_one.gs');

// Read source files
const codeGs = fs.readFileSync(CODE_GS_PATH, 'utf8');
const indexHtml = fs.readFileSync(INDEX_HTML_PATH, 'utf8');

// Base64 encode the HTML
const htmlBase64 = Buffer.from(indexHtml, 'utf8').toString('base64');

// Create the all-in-one file header
const header = `/**
 * CEE Mock Portal - All-in-One Apps Script deployment.
 * This single file contains both backend (Code.gs) and frontend (index.html),
 * with the UI base64-encoded into EMBEDDED_HTML and decoded at runtime.
 *
 * Generated by tools/build.js from Code.gs + index.html
 *
 * DEPLOYMENT:
 * 1. Create a new Google Apps Script project.
 * 2. Copy ALL of this file's content into the editor (replace Code.gs).
 * 3. Deploy as Web App: Execute as "Me", Access "Anyone".
 * 4. Save the Web App URL and paste it into the CONFIG object below if needed.
 *
 * To change the UI, edit index.html and re-run: node tools/build.js
 */

`;

// Build the config section with placeholders
const configSection = `// ==================== CONFIGURATION ====================
var CONFIG = {
  // Replace with your deployed Web App URL after deployment
  WEB_APP_URL: 'https://script.google.com/macros/s/AKfycbwgnUluOVaruBxQijfMnxtbng0pZ0SL3cKv9aYrMTjpzjdKedUMGZl2rwBgGNHl_CQS/exec',

  // Support email for reply-to on all outgoing emails
  EMAIL_REPLY_TO: 'support@cee-notes.cprecnepal.org.np',

  // Sheet ID will be auto-created on first run if not set
  SHEET_ID: ''
};
// =======================================================

`;

// Find where EMBEDDED_HTML is defined in the original code and replace it
let output = codeGs;

// Replace the EMBEDDED_HTML line with our generated one (handles empty string or existing base64)
const regex = /var EMBEDDED_HTML\s*=\s*['"][A-Za-z0-9+/=]*['"];?/g;
output = output.replace(regex, `var EMBEDDED_HTML = '${htmlBase64}';`);

// Add header and config if not already present
if (!output.startsWith('/**')) {
  output = header + configSection + output;
} else if (!output.includes('var CONFIG = {')) {
  // Insert config after the initial comment block
  const firstVarIndex = output.indexOf('var ');
  if (firstVarIndex > 0) {
    output = output.substring(0, firstVarIndex) + configSection + output.substring(firstVarIndex);
  }
}

// Write the output file
fs.writeFileSync(OUTPUT_PATH, output, 'utf8');

console.log('✓ Built cee_mock_all_in_one.gs successfully');
console.log(`  - HTML size: ${indexHtml.length} bytes`);
console.log(`  - Base64 size: ${htmlBase64.length} bytes`);
console.log(`  - Output size: ${output.length} bytes`);
