/** Builds the single-file deliverable: Code.gs + base64(index.html) -> cee_mock_all_in_one.gs
 *  Base64 is wrapped into short quoted lines because the Apps Script editor and
 *  copy/paste paths get unhappy with one 80k-character line. */
'use strict';
const fs = require('fs');
const path = require('path');
const zlib = require('zlib');

/* Sources and output are resolved by tools/paths.js so the same rig works in the
 *  flat layout (Code.gs + index.html at the root) and in the split layout used by
 *  the GitHub Pages repo (src/ + dist/, root index.html = the Pages door). */
const P = require('./paths.js');
const read = f => fs.readFileSync(f, 'utf8');
const code = read(P.CODE);
const html = read(P.HTML);

if (!/function doGet\(/.test(code)) throw new Error('Code.gs does not look like the portal backend');
if (!/CEE Mock Portal/.test(html)) throw new Error('index.html does not look like the portal');

const b64 = Buffer.from(html, 'utf8').toString('base64');
// round-trip check before we ship it
const back = Buffer.from(b64, 'base64').toString('utf8');
if (back !== html) throw new Error('base64 round-trip mismatch');

const PER = 116;
const lines = b64.match(new RegExp(`[\\s\\S]{1,${PER}}`, 'g'));
const literal = "  '" + lines.join("'\n  + '") + "'";
const b64size = b64.length;

const header = `/* ==================================================================
 *  CEE MOCK PORTAL - SINGLE FILE BUILD  (generated - do not hand-edit)
 *  ------------------------------------------------------------------
 *  This one file is the whole portal: the Apps Script backend AND the
 *  student/teacher UI, with the UI base64-encoded into EMBEDDED_HTML and
 *  decoded by doGet() through Utilities.base64Decode.
 *
 *  Generated by tools/build.js from Code.gs + index.html
 *    index.html : ${(html.length / 1024).toFixed(1)} KB of portal UI
 *    base64     : ${(b64size / 1024).toFixed(1)} KB, ${lines.length} lines of <= ${PER} chars
 *    total file : ${(html.length + code.length) / 1024 | 0} KB of source
 *
 *  DEPLOY
 *    1. Google Sheet -> Extensions -> Apps Script -> delete the default file,
 *       paste this whole file, save.
 *    2. (optional) set CONFIG.SHEET_ID to this sheet's id; then Run setup_ once
 *       to create the tabs and seed the question bank.
 *    3. Deploy -> New deployment -> Web app -> Execute as: Me,
 *       Who has access: Anyone  -> copy the /exec URL to your students.
 *    4. Open the URL, register with an address listed in CONFIG.ADMIN_EMAILS
 *       (the very first registration becomes an approved teacher automatically).
 *    5. After ANY later code change: Deploy -> Manage deployments -> Edit ->
 *       Version "New version" -> Deploy.  The /exec URL keeps serving the old
 *       version until you do; a bare save is not enough.
 *
 *  MAIL (the portal mails students and teachers directly)
 *    Reply-To is always CONFIG.MAIL_REPLY_TO, which works with no setup.  Using
 *    CONFIG.MAIL_FROM as the visible sender requires that address to be added in
 *    Gmail -> Settings -> Accounts and Import -> "Send mail as" (verify through
 *    your domain's SMTP).  If Gmail refuses it, sendMail_ retries without "from"
 *    so no mail is ever lost, and remembers that for the rest of the execution.
 *    Teacher -> System -> "Portal link & support" edits CONFIG.PORTAL_URL and the
 *    support address at runtime (Script Properties) and fires one test mail, so
 *    neither needs a re-deploy.  Self-test: <your /exec URL>?health=1 -> mail.
 *
 *  To change the UI, edit index.html and re-run:  node tools/build.js
 *  ================================================================== */

/** The whole portal UI, base64-encoded (decoded in getPortalHtml_()). */
var EMBEDDED_HTML =
${literal};

`;
const out = header + code;
fs.mkdirSync(path.dirname(P.BUILT), { recursive: true });
fs.writeFileSync(P.BUILT, out);

const longest = out.split('\n').reduce((a, l) => Math.max(a, l.length), 0);
console.log('wrote ' + P.name(P.BUILT) + (P.SPLIT ? '  [split layout: src -> dist]' : ''));
console.log('  bytes      :', out.length, '(' + (out.length / 1024).toFixed(1) + ' KB)');
console.log('  lines      :', out.split('\n').length);
console.log('  longest line:', longest, '(editor-safe: ' + (longest < 1000) + ')');
console.log('  gzip check :', (zlib.gzipSync(out).length / 1024).toFixed(1) + ' KB compressed');
